# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: SetTrans Translation Services
email: settrans.eits@gmail.com
phone: "+6285691306716"
description: > # this means to ignore newlines until "baseurl:"
   Solution to your English-Indonesian language translation needs.  <br/>  
   Not sure? Just ask us.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://settrans.github.io"

# Build settings
markdown: kramdown
